# Higher noise and longer horizon for stress-testing detectors
start: '2025-03-01 00:00'
periods: 576  # two days at 5-minute resolution
freq: '5min'
seed: 2025
loss_rate: 0.03
noise:
  source:
    sigma_abs: 1.5
    sigma_rel: 0.015
  consumer:
    sigma_abs: 0.3
    sigma_rel: 0.2
profiles:
  num_harmonics: 4
  dow_factors:
    '0': 0.95
    '1': 0.98
    '2': 1.0
    '3': 1.02
    '4': 1.05
    '5': 1.1
    '6': 1.15
  season_strength: 0.25
