# Configuration emphasising steady demand with minimal measurement noise
# Useful for isolating effects of injected leak events
start: '2025-05-15 06:00'
periods: 288
freq: '10min'
seed: 77
loss_rate: 0.01
noise:
  source:
    sigma_abs: 0.1
    sigma_rel: 0.002
  consumer:
    sigma_abs: 0.05
    sigma_rel: 0.05
profiles:
  num_harmonics: 1
  dow_factors:
    '0': 1.0
    '1': 1.0
    '2': 1.0
    '3': 1.0
    '4': 1.0
    '5': 0.95
    '6': 0.9
  season_strength: 0.05
