# Higher weekend consumption with modest weekday demand and measurement noise
start: '2025-07-01 00:00'
periods: 2016  # two weeks at 10-minute resolution
freq: '10min'
seed: 1337
loss_rate: 0.015
noise:
  source:
    sigma_abs: 0.5
    sigma_rel: 0.01
  consumer:
    sigma_abs: 0.2
    sigma_rel: 0.12
profiles:
  num_harmonics: 3
  dow_factors:
    '0': 0.9
    '1': 0.95
    '2': 1.0
    '3': 1.0
    '4': 1.05
    '5': 1.25
    '6': 1.35
  season_strength: 0.4
